name: CI for dev branch

on:
  push:
    branches:
      - dev

jobs:
  build_check:
    runs-on: ubuntu-latest
    name: Check if project builds
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # You can optionally add steps here to lint or test your static files if required

      - name: Merge to prod branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git fetch
          git checkout prod
          git merge --no-ff dev
          git push

